# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Conda Tests

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: False
      matrix:
        python-version: ["3.6","3.7","3.8","3.9"]

    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v2"
      - name: Setup Python 🐍
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies 🔧
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade repo_helper
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda update -q conda

          $CONDA/bin/conda config --add channels domdfcoding

          $CONDA/bin/conda config --add channels conda-forge


      - name: "Build and install package"
        run: |
          # This mess is only necessary because conda won't fix it themselves
          # https://github.com/conda/conda/issues/1884
          python -m repo_helper build --conda --out-dir conda-bld/noarch
           $CONDA/bin/conda install consolekit -c local -y || exit 1
